Terminal logging
FormingWorlds/JANUS pull request #52
Opened 2024-08-09 17:41 UTC by nichollsh

JANUS now logs information to the terminal (stdout, stderr) via the `logging` module, rather than with the `print` function. This integrates better with PROTEUS and offers more flexibility going forward.

This means that PROTEUS will no longer need to redirect stdout to its own logger when JANUS is called. Closes #46.

Replaced "SOCRATES" env variable with "RAD_DIR" for consistency with other modules (although the name is probably less intuitive). Closes #51.

2024-08-12 07:10 UTC, stefsmeets requested changes
Nice effort on cleaning up the print statements!

I have one concern with this PR. 

That is the the non-idiomatic way to define the logger (see [here](https://docs.python.org/3/library/logging.html) for more info). 

```
import logging
logger = logging.getLogger(__name__)
```

This way the logger can be defined by any tool using the library. If JANUS is used as a library, it should not be the one setting up the logger. Instead, the logger should be set up by the CLI or PROTEUS or any other code that calls JANUS.

2024-08-28 15:41 UTC, nichollsh commented
Updated this PR to resolve the issues raised above. The loggers are now assigned names in the format of `"fwl."+__name__` as recommended by the Python documentation for libraries.

https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

This means that it's still clear where in the code a logging call is made, but only a single handler is required at a time (or two if you are also logging to a file). There will be a corresponding update to PROTEUS.

Some other minor changes including refactoring of some functions and documentation.

2024-08-29 06:30 UTC, stefsmeets approved these changes
Looks great! Definitely a nice step forward, and clever idea by prefixing `fwl.` to the logger name. This seems in line with documentation on how it was intended to be used, curious to see how it will work in practice 😅

2024-08-29 06:30 UTC, stefsmeets commented on src/janus/utils/logs.py
> +        raise Exception("Invalid log level '%s'"%level)
```suggestion
        raise ValueError("Invalid log level '%s'"%level)
```

2024-08-29 07:54 UTC, merged